---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "studio.fullname" . }}-frontend-app
  labels:
    release: {{ .Release.Name }}
    app: {{ template "studio.fullname" . }}
    tier: frontend
    monitoring: prometheus
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    interval: 15s
    port: ""
  selector:
    matchLabels:
      release: {{ .Release.Name }}
      app: {{ template "studio.fullname" . }}
      tier: frontend